apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-sauce
  namespace: secret-sauce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-sauce
  template:
    metadata:
      labels:
        app: secret-sauce
    spec:
      containers:
      - name: secret-sauce
        image: thevestedleopard/secret-sauce
---
apiVersion: v1
kind: Service
metadata:
  name: secret-sauce
  namespace: secret-sauce
spec:
  ports:
  - name: http
    targetPort: 80
    port: 80
  selector:
    app: secret-sauce
